apiVersion: apps/v1
kind: Deployment
metadata:
  name: px-backup-notifier
  namespace: operator-system
  labels:
    controller: px-backup-notifier
spec:
  selector:
    matchLabels:
      controller: px-backup-notifier
  replicas: 1
  template:
    metadata:
      labels:
        controller: px-backup-notifier
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - command:
        - /controller
        env:
          - name: "SCHEDULE_TIMEOUT"
            value: "45"
          - name: INGRESS_URL
            value: backupui-dev01.baas.portworx.dev
          - name: "WEBHOOK_URL"
            value: "http://tenant-deployment-notify-eventsource-svc.argo-events:8080/status"
          - name: "nsLabel"
            value: ""
          - name: "RETRY_DELAY"
            value: "20"
          - name: "CLIENT_ID"
            value: ""
          - name: "USERNAME"
            value: ""
          - name: "PASSWORD"
            value: ""
          - name: "TOKEN_DURATION"
            value: "365d"
          - name: "TOKEN_URL"
            value: "https://backup.baas.portworx.dev/auth/realms/master/protocol/openid-connect/token"
          - name: "SCHEDULE_URL"
            value: "https://backup.baas.portworx.dev/lhBackend/pxBackup/schedules/getItem?org_id=default&endpoint=px-backup:10002"
        image: px-backup-notifier:latest
        name: px-backup-notifier
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      serviceAccountName: px-backup-notifier
      terminationGracePeriodSeconds: 10
